### ISSUE TITLE
Team members

### ISSUE THREAD

**Issue by gdvl777** [gdvl777/space_traveler#99]
In this [project](https://github.com/gdvl777/space_traveler), these are our members:
- [Kevin Cruz](https://www.linkedin.com/in/kevin-cruz-25159a201/)
- [Animashaun Fisayo](https://www.linkedin.com/in/fmanimashaun/)
- [@gdvl777](https://github.com/gdvl777)

**Comment by AbdusSattar-70** [comment]
## APPROVED 🏆 
Hi Team @gdvl777 @fmanimashaun @EvansSnave , 

Your Kanban Board setup is complete!  There is nothing else to say other than... it's time to close the issue and start working on it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
